.TH "Bool_Init" 3 "Thu Aug 8 2019" "Mapping" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bool_Init \- Struct returned on \fBCamera::Init()\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Camera\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBt265\fP"
.br
.RI "\fIboolean value for T265 \fP"
.ti -1c
.RI "bool \fBd435\fP"
.br
.RI "\fIboolean value for D435 \fP"
.in -1c
.SH "Detailed Description"
.PP 
Struct returned on \fBCamera::Init()\fP 

Struct contains two boolean values each denoting whether the corresponding camera stream was started\&. 
.PP
\fBSee also:\fP
.RS 4
\fBCamera::Init()\fP 
.RE
.PP

.PP
Definition at line 55 of file Camera\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Bool_Init::d435"

.PP
boolean value for D435 
.PP
Definition at line 59 of file Camera\&.hpp\&.
.SS "bool Bool_Init::t265"

.PP
boolean value for T265 
.PP
Definition at line 57 of file Camera\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mapping from the source code\&.
