.TH "include/Cam_Writer.hpp" 3 "Mon Jul 22 2019" "Mapping" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Cam_Writer.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sys/ipc\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <semaphore\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <librealsense2/rs\&.hpp>\fP
.br
\fC#include 'Camera\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mapping from the source code\&.
