.TH "include/Helper.hpp" 3 "Thu Aug 8 2019" "Mapping" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Helper.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Camera\&.hpp'\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPair< A, B >\fP"
.br
.RI "\fITemplate Class for Pairs\&. \fP"
.ti -1c
.RI "class \fBMap_FE\fP"
.br
.RI "\fIVirtual class Parent of \fBCPU_FE\fP and \fBGPU_FE\fP classes\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCUDA_CALL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CUDA_CALL"

.PP
Definition at line 7 of file Helper\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Mapping from the source code\&.
