.TH "Writer" 3 "Mon Jul 22 2019" "Mapping" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Writer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cam_Writer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "rs2::frameset \fBfs_d435\fP"
.br
.ti -1c
.RI "rs2::frameset \fBfs_t265\fP"
.br
.ti -1c
.RI "\fBCamera\fP \fBC\fP"
.br
.ti -1c
.RI "\fBBool_Init\fP \fBb\fP"
.br
.ti -1c
.RI "int \fBfd_d435\fP"
.br
.ti -1c
.RI "int \fBfd_t265\fP"
.br
.ti -1c
.RI "void * \fBptr_d435\fP"
.br
.ti -1c
.RI "void \fBptr_t265\fP"
.br
.ti -1c
.RI "sem_t * \fBsemptr_d435\fP"
.br
.ti -1c
.RI "sem_t \fBsemptr_t265\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Cam_Writer\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Writer::Init ()\fC [inline]\fP"

.PP
Definition at line 34 of file Cam_Writer\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBool_Init\fP Writer::b"

.PP
Definition at line 27 of file Cam_Writer\&.hpp\&.
.SS "\fBCamera\fP Writer::C"

.PP
Definition at line 26 of file Cam_Writer\&.hpp\&.
.SS "int Writer::fd_d435"

.PP
Definition at line 29 of file Cam_Writer\&.hpp\&.
.SS "int Writer::fd_t265"

.PP
Definition at line 29 of file Cam_Writer\&.hpp\&.
.SS "rs2::frameset Writer::fs_d435"

.PP
Definition at line 25 of file Cam_Writer\&.hpp\&.
.SS "rs2::frameset Writer::fs_t265"

.PP
Definition at line 25 of file Cam_Writer\&.hpp\&.
.SS "void* Writer::ptr_d435"

.PP
Definition at line 30 of file Cam_Writer\&.hpp\&.
.SS "void Writer::ptr_t265"

.PP
Definition at line 30 of file Cam_Writer\&.hpp\&.
.SS "sem_t* Writer::semptr_d435"

.PP
Definition at line 31 of file Cam_Writer\&.hpp\&.
.SS "sem_t Writer::semptr_t265"

.PP
Definition at line 31 of file Cam_Writer\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mapping from the source code\&.
